---
#
# This playbook clones a new VM from a template
#
- name: Clone a new VM from a template
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_ip
      prompt: vCenter IP or hostname
      private: no

    - name: vcenter_username
            prompt: vCenter username
      default: "{{ vcenter_username }}"
      private: no

    - name: vcenter_password
      prompt: vCenter password
      private: yes

    - name: datacenter
      prompt: VMWare datacenter
      private: no

    - name: datastore
      prompt: VMWare datastore
      private: no

    - name: template_name
      prompt: Template name
      private: no

    - name: new_template_name
      prompt: New template name
      private: no

    - name: folder_name
      prompt: Folder name
      private: no

    - name: cluster_name
      prompt: Cluster name
      private: no

  tasks:
  - name: "Clone Template from template"
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      template: "{{ template_name }}"
      name: "{{ new_template_name }}"
      datacenter: "{{ datacenter }}"
      folder: "{{ folder_name }}"
      cluster: "{{ cluster_name }}"
      is_template: yes
    delegate_to: localhost
    connection: local
