---
#
# This playbook shows real VM size
#
- name: Get VM size
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_ip
      prompt: vCenter IP or hostname
      private: no

    - name: vcenter_username
            prompt: vCenter username
      default: "{{ vcenter_username }}"
      private: no

    - name: vcenter_password
      prompt: vCenter password
      private: yes

    - name: datacenter
      prompt: VMWare datacenter
      private: no

    - name: vm_name
      prompt: VM Name
      private: no

  tasks:
  - name: Get VM size
    community.vmware.vmware_guest_disk_info:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vm_name }}"
    delegate_to: localhost
    connection: local
    register: disk_info

  - name: "Set default value to total_storage_size"
    set_fact:
      total_storage_size: "0"

  - name: "Set value to total_storage_size"
    set_fact:
      total_storage_size: "{{ total_storage_size | int + item.value.capacity_in_kb | int }}"
    with_dict: "{{ disk_info.guest_disk_info }}"

  - name: "Convert value to Gb"
    set_fact:
      total_storage_size: "{{ total_storage_size | int / (1024 * 1024) }}"

  - name: "Print VM size"
    debug:
      msg: "Total storage size of '{{ vm_name }}' is {{ total_storage_size | int }} Gb"
